# Reproducible reporting with Quarto

## Learn Quarto

Reproducible reporting is the starting point for robust interactive
data science. Perform the following tasks:

 * If you are entirely new to Quarto, take
   [this short tutorial](https://quarto.org/docs/get-started/hello/rstudio.html)
   to get introduced to the most important functions within Quarto.
   Then experiment with different options from the
   [Quarto cheatsheet](https://res.cloudinary.com/dyd911kmh/image/upload/v1676540721/Marketing/Blog/Quarto_Cheat_Sheet.pdf).

 * Create a Quarto template in RStudio, and render it into a
   document (markdown, PDF, docx or other format). In case you are new
   to Quarto, its documentation provides guidelines to use Quarto with the
   R language ([here](https://quarto.org/docs/computations/r.html))
   and the RStudio IDE ([here](https://quarto.org/docs/tools/rstudio.html)).

 * Further examples are tips for Quarto are available in [this online tutorial](https://appsilon.com/r-quarto-tutorial/)
   to interactive reproducible reporting.

## Additional material on Rmarkdown

Being able to use Quarto in R partly relies on your previous knowledge of Rmarkdown. The following resources can help you get familiar with Rmarkdown:

 * [online tutorial](https://www.markdowntutorial.com/)
 * [cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
 * [documentation](https://rmarkdown.rstudio.com/lesson-1.html)
 * [Dr. C Titus Brown's tutorial](https://rpubs.com/marschmi/RMarkdown)

